name: Build Program

on:
  push:
    branches: [$default-branch]
  pull_request:
    branches: [$default-branch]

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install MinGW on Windows
        run: choco install mingw
      - name: Run Makefile on Windows
        run: make
      - name: Upload build artifact from Windows
        uses: actions/upload-artifact@v4
        with:
          name: cmatrix-windows
          path: cmatrix.exe
