name: Release Program

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup MSYS2
        uses: msys2/setup-msys2@v2
        with:
          update: true
          install: >-
            mingw-w64-x86_64-gcc
            make

      - name: Build project
        shell: msys2 {0}
        run: make

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: cmatrix-windows
          path: cmatrix.exe

      - name: Create zip
        run: Compress-Archive -Path cmatrix.exe -DestinationPath WinCMatrix.zip

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: wincmatrix@${{ github.ref_name }}
          generate_release_notes: true
          files: WinCMatrix.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}